###################################################
# This creates and stands up the development
# docker container. Depends on the Dockerfile and
# docker-start.sh files.
###################################################

services:
  actual:
    image: actualbudget/actual-server:latest
    ports:
      - "5006:5006"
    volumes:
      - actual_data:/data
    restart: unless-stopped

volumes:
  actual_data:
